#!/bin/bash

#mktree folder/subfolder[1..3]/subsubfolder[4..5]/files[3..4]
#regexp="(\w+)(\[\d+\.\.\d+\])?"


function mktree() {
  tmpl=$1
  num=$2
  shift
  shift

  for (( i=0; i<num; i++ ))
  do
    name=$tmpl$i

    if [[ $# -gt 0 ]]; then
      mkdir $name
    else
      touch $name
    fi
  done

  for dir in *; do
    if [[ -d $dir ]]; then
      cd $dir
      mktree $@
      cd ..
    fi
  done
}

parent=$1
mkdir $parent
shift
cd $parent

mktree $@

cd ..